apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: vm-rancheronline
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: "admin"
          passwd: "admin"
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
      registration:
        emulate-tpm: true
        emulated-tpm-seed: 2
  machineName: vm-rancheronline
  machineInventoryLabels:
    location: "nue_vo_apsys4"
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
